zsh: print to stderr in scripts

diff --git a/zsh/bin/launchctl-reload b/zsh/bin/launchctl-reload
--- a/zsh/bin/launchctl-reload
+++ b/zsh/bin/launchctl-reload
@@ -14,7 +14,7 @@ __basename() {
 
 config_path=${1:-}
 if [[ -z $config_path ]]; then
-  echo "usage: $(__basename "$0" "") <config>"
+  echo "usage: $(__basename "$0" "") <config>" >&2
   exit 1
 fi
 
@@ -22,14 +22,14 @@ if [[ ! -f $config_path ]]; then
   if [[ -f "$HOME/Library/LaunchAgents/$config_path" ]]; then
     config_path="$HOME/Library/LaunchAgents/$config_path"
   else
-    echo "Unable to find configuration $config_path"
+    echo "Unable to find configuration $config_path" >&2
     exit 1
   fi
 fi
 
-echo "Config: $config_path"
-echo "Unloading."
+echo "Config: $config_path" >&2
+echo "Unloading." >&2
 launchctl unload "$config_path"
 
-echo "Loading."
+echo "Loading." >&2
 launchctl load "$config_path"
diff --git a/zsh/bin/pdfopt b/zsh/bin/pdfopt
--- a/zsh/bin/pdfopt
+++ b/zsh/bin/pdfopt
@@ -30,19 +30,19 @@ __basename() {
 
 file=${1:-}
 if [[ -z $file ]]; then
-  echo "usage: $(basename "$0") <file> [output-file]"
+  echo "usage: $(basename "$0") <file> [output-file]" >&2
   exit 1
 fi
 
 if [[ ! -f $file ]]; then
-  echo "File not found."
+  echo "File not found." >&2
   exit 1
 fi
 
 output_file=${2:-}
 if [[ -z $output_file ]]; then
   output_file="$(__dirname "$file")/$(__basename "$file" ".pdf")-opt.pdf"
-  echo "$output_file"
+  echo "$output_file" >&2
 fi
 
 pdfsettings="/ebook"
